const SUPABASE_URL="https://qemcatfhcmnrckufsjiz.supabase.co";
const SUPABASE_KEY="sb_publishable_g0IEeggLJZtytr-vHQALHg_WQKk31b_";
const loginPanel=document.querySelector("#login-panel"),dashboard=document.querySelector("#dashboard"),loginForm=document.querySelector("#login-form"),loginMessage=document.querySelector("#login-message"),recordBody=document.querySelector("#record-body"),emptyState=document.querySelector("#empty-state"),shopFilter=document.querySelector("#shop-filter"),prizeFilter=document.querySelector("#prize-filter"),dateStart=document.querySelector("#date-start"),dateEnd=document.querySelector("#date-end"),prizeGrid=document.querySelector("#prize-grid"),toast=document.querySelector("#toast");
let accessToken=sessionStorage.getItem("bobing_admin_token")||"",allRows=[],filteredRows=[];
const safe=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
function notify(text){toast.textContent=text;toast.classList.add("show");clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.classList.remove("show"),2200)}
function authHeaders(extra={}){return{apikey:SUPABASE_KEY,Authorization:`Bearer ${accessToken}`,...extra}}
async function isAdmin(){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/is_bobing_admin`,{method:"POST",headers:authHeaders({"Content-Type":"application/json"}),body:"{}"});return response.ok&&await response.json()===true}
async function loadAll(){
  const rows=[];let from=0;
  while(true){const response=await fetch(`${SUPABASE_URL}/rest/v1/bobing_results?select=id,created_at,nickname,phone,shop_code,dice,prize,original_prize,actual_prize,message,page_version&order=created_at.desc`,{headers:authHeaders({Range:`${from}-${from+999}`})});if(!response.ok)throw new Error("数据读取失败");const page=await response.json();rows.push(...page);if(page.length<1000)break;from+=1000}
  allRows=rows;populateFilters();applyFilters();notify("数据已更新");
}
function populateFilters(){const currentShop=shopFilter.value,currentPrize=prizeFilter.value;const shops=[...new Set(allRows.map(r=>r.shop_code).filter(Boolean))].sort();const prizes=[...new Set(allRows.map(r=>r.actual_prize||r.prize).filter(Boolean))].sort();shopFilter.innerHTML='<option value="">全部店铺</option>'+shops.map(v=>`<option>${safe(v)}</option>`).join("");prizeFilter.innerHTML='<option value="">全部实际奖项</option>'+prizes.map(v=>`<option>${safe(v)}</option>`).join("");shopFilter.value=shops.includes(currentShop)?currentShop:"";prizeFilter.value=prizes.includes(currentPrize)?currentPrize:""}
function applyFilters(){const start=dateStart.value?new Date(`${dateStart.value}T00:00:00`):null,end=dateEnd.value?new Date(`${dateEnd.value}T23:59:59.999`):null;filteredRows=allRows.filter(row=>{const time=new Date(row.created_at),actual=row.actual_prize||row.prize;return(!start||time>=start)&&(!end||time<=end)&&(!shopFilter.value||row.shop_code===shopFilter.value)&&(!prizeFilter.value||actual===prizeFilter.value)});render()}
function render(){const winners=filteredRows.filter(r=>(r.actual_prize||r.prize)!=="未中奖"&&r.prize!=="再接再厉"),players=new Set(filteredRows.map(r=>`${r.shop_code||""}|${r.nickname||""}`));document.querySelector("#total-count").textContent=filteredRows.length;document.querySelector("#winner-count").textContent=winners.length;document.querySelector("#player-count").textContent=players.size;document.querySelector("#winner-rate").textContent=filteredRows.length?`${(winners.length/filteredRows.length*100).toFixed(1)}%`:"0%";document.querySelector("#result-summary").textContent=`共 ${filteredRows.length} 条记录`;const counts={};filteredRows.forEach(r=>{const p=r.actual_prize||r.prize;counts[p]=(counts[p]||0)+1});prizeGrid.innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([name,count])=>`<div class="prize-item"><span>${safe(name)}</span><strong>${count}</strong></div>`).join("")||'<div class="prize-item"><span>暂无奖项数据</span><strong>0</strong></div>';recordBody.innerHTML=filteredRows.map(row=>`<tr><td>${new Date(row.created_at).toLocaleString("zh-CN",{hour12:false})}</td><td>${safe(row.nickname)}</td><td>${safe(row.shop_code||"未填写")}</td><td>${safe(row.original_prize||row.prize)}</td><td>${safe(row.actual_prize||row.prize)}</td><td>${safe(Array.isArray(row.dice)?row.dice.join("、"):row.dice)}</td><td>${safe(row.message)}</td></tr>`).join("");emptyState.hidden=filteredRows.length!==0}
function csvCell(value){let text=String(value??"");if(/^[=+\-@]/.test(text))text=`'${text}`;return`"${text.replace(/"/g,'""')}"`}
function exportCsv(){if(!filteredRows.length){notify("当前没有可导出的记录");return}const headers=["时间","姓名/昵称/手机号","店铺编码","原始中奖结果","实际发放奖品","骰子","说明","页面版本"],lines=filteredRows.map(r=>[new Date(r.created_at).toLocaleString("zh-CN",{hour12:false}),r.nickname,r.shop_code||"",r.original_prize||r.prize,r.actual_prize||r.prize,Array.isArray(r.dice)?r.dice.join("-"):r.dice,r.message,r.page_version].map(csvCell).join(","));const blob=new Blob(["\ufeff"+[headers.map(csvCell).join(","),...lines].join("\r\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`博饼记录_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);notify("CSV 已导出")}
async function enterDashboard(){if(!accessToken||!await isAdmin())throw new Error("该账号没有后台权限");loginPanel.hidden=true;dashboard.hidden=false;await loadAll()}
loginForm.addEventListener("submit",async event=>{event.preventDefault();loginMessage.textContent="正在登录…";try{const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify({email:document.querySelector("#email").value.trim(),password:document.querySelector("#password").value})});const data=await response.json();if(!response.ok)throw new Error("邮箱或密码错误");accessToken=data.access_token;sessionStorage.setItem("bobing_admin_token",accessToken);await enterDashboard();loginMessage.textContent="";document.querySelector("#password").value=""}catch(error){accessToken="";sessionStorage.removeItem("bobing_admin_token");loginMessage.textContent=error.message}});
[dateStart,dateEnd,shopFilter,prizeFilter].forEach(el=>el.addEventListener("change",applyFilters));
document.querySelector("#reset").addEventListener("click",()=>{dateStart.value="";dateEnd.value="";shopFilter.value="";prizeFilter.value="";applyFilters()});document.querySelector("#refresh").addEventListener("click",()=>loadAll().catch(()=>notify("刷新失败，请重新登录")));document.querySelector("#export").addEventListener("click",exportCsv);document.querySelector("#logout").addEventListener("click",()=>{sessionStorage.removeItem("bobing_admin_token");location.reload()});
if(accessToken)enterDashboard().catch(()=>{accessToken="";sessionStorage.removeItem("bobing_admin_token")});
